metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 25s
  enabled: true


output.logstash:
  hosts: ["containerlogstash:5044"]

#processors:
#  - add_cloud_metadata: ~

#output.elasticsearch:
#  hosts: 'containerelasticsearch:9200'