filebeat.inputs:

- type: log
  enabled: true
  name: master
  fields:
    id: master
  paths:
    - /var/log/spark_master/*


- type: log
  enabled: true
  name: wrk1
  fields:
    id: wrk1
  paths:
    - /var/log/spark_worker1/*
    
- type: log
  enabled: true
  name: wk2
  fields:
    id: wk2
  paths:
    - /var/log/spark_workerZ/*
  
output.logstash:
  hosts: ["container_logstash:5044"]
  #ssl.certificate_authorities: ["/etc/ca.crt"]
  #ssl.certificate: "/etc/client.crt"
  #ssl.key: "/etc/client.key"
  #ssl.supported_protocols: "TLSv1.2"
  
#output.elasticsearch.hosts: ["https://container_elasticsearch:9200"]
#output.elasticsearch.ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]
#output.elasticsearch.ssl.certificate: "/etc/pki/client/cert.pem"
#output.elasticsearch.ssl.key: "/etc/pki/client/cert.key"
  
setup.kibana.host: "http://container_kibana:5601"
setup.kibana.ssl.enabled: false
#setup.kibana.ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]
#setup.kibana.ssl.certificate: "/etc/pki/client/cert.pem"
#setup.kibana.ssl.key: "/etc/pki/client/cert.key"
  
setup.dashboards.enabled: true
setup.dashboards.beat: "filebeat"
setup.dashboards.index: "filebeat-*"
