filebeat.inputs:
- type: log
  enabled: true
  fields:
    id: master
  paths:
    - /var/log/*.log
    
- type: log
  enabled: true
  fields:
    id: wrk1
  paths:
    - /spark/logs/*
  
output.logstash:
  hosts: ["elk:5044"]
  
setup.kibana:
  host: "elk:5601"
  
setup.dashboards.enabled: true
setup.dashboards.beat: "filebeat"
setup.dashboards.index: "master-*"